title: Calculadora FAP
description: |
  <p>Desenvolvido por Eduardo Cardoso.</p>

    <p>Precisa de ajuda com o FAP? Entre em contato:</p>

    <p><a href="https://www.linkedin.com/in/eduardo-pereira-cardoso-9a5a12b3/">LinkedIn - Eduardo Cardoso</a></p>
    
logo: Logo Calculadora.jpeg
remote_theme: dudapcardoso/minimal
