title: Calculadora FAP
description: |
    Desenvolvido por Eduardo Cardoso.
    Precisa de ajuda com o FAP? Entre em contato pelo QRCODE.
logo: Logo Calculadora.jpeg
remote_theme: dudapcardoso/minimal
show_downloads: false
